#sales_dataset: ETL configurations of supervised sales dataset.
#keys of input_dataset are function names (cannot be renamed) & values are function arguments (value can be null to skip except for read_dataset)
#delete_column/select_column: arguments can be in front or under as list_of_cols
#list_of_cols: list or string with multiple columns separated by | (refer doc string for further details)
input_dataset:
  read_dataset:
    file_path: "data/sales_dataset/csv"
    file_type: csv
    file_configs:
      header: True
      delimiter: ","
      inferSchema: True
  delete_column: [ 'Outlet_Identifier' ]
  select_column: null


anovos_basic_report:
  basic_report: False
  report_args:
    id_col: Item_Identifier
    label_col: sales
    event_label: '>2k'
    skip_corr_matrix: True
    output_path: report_stats

#if anovos_basic_report.basic_report is True, then all configs below are ignored.
stats_generator:
  metric: [ 'global_summary','measures_of_counts','measures_of_centralTendency','measures_of_cardinality'
    ,       'measures_of_percentiles','measures_of_dispersion','measures_of_shape' ]
  metric_args:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier' ]

quality_checker:
  duplicate_detection:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier' ]
    treatment: True

  nullRows_detection:
    list_of_cols: all
    drop_cols: [ ]
    treatment: True
    treatment_threshold: 0.75

  invalidEntries_detection:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier' ]
    treatment: True
    output_mode: replace

  IDness_detection:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier' ]
    treatment: True
    treatment_threshold: 0.9

  biasedness_detection:
    list_of_cols: all
    drop_cols: [ 'sales' ]
    treatment: True
    treatment_threshold: 0.98

  outlier_detection:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier','sales' ]
    detection_side: upper
    detection_configs:
      pctile_lower: 0.05
      pctile_upper: 0.90
      stdev_lower: 3.0
      stdev_upper: 3.0
      IQR_lower: 1.5
      IQR_upper: 1.5
      min_validation: 2
    treatment: True
    treatment_method: value_replacement
    pre_existing_model: False
    model_path: NA
    output_mode: replace

  nullColumns_detection:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier','sales' ]
    treatment: True
    treatment_method: MMM
    treatment_configs:
      method_type: median
      pre_existing_model: False
      model_path: NA
      output_mode: replace


association_evaluator:

  correlation_matrix:
    list_of_cols: all
    drop_cols: [ 'Item_Identifier' ]

  IV_calculation:
    list_of_cols: all
    drop_cols: Item_Identifier
    label_col: sales
    event_label: '>2k'
    encoding_configs:
      bin_method: equal_frequency
      bin_size: 10
      monotonicity_check: 0

  IG_calculation:
    list_of_cols: all
    drop_cols: Item_Identifier
    label_col: sales
    event_label: '>2k'
    encoding_configs:
      bin_method: equal_frequency
      bin_size: 10
      monotonicity_check: 0

  variable_clustering:
    list_of_cols: all
    drop_cols: Item_Identifier|sales


drift_detector:
  drift_statistics:
    configs:
      list_of_cols: all
      drop_cols: [ 'Item_Identifier','sales' ]
      method_type: all
      threshold: 0.1
      bin_method: equal_range
      bin_size: 10
      pre_existing_source: False
      source_path: NA

    source_dataset:
      read_dataset:
        file_path: "data/sales_dataset/source"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True
      delete_column: [ 'Outlet_Identifier' ]
      select_column: null

  stability_index:

    configs:
      metric_weightages:
        mean: 0.5
        stddev: 0.3
        kurtosis: 0.2
      existing_metric_path: ''
      appended_metric_path: 'si_metrics'
      threshold: 2

    dataset1:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/0"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset2:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/1"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema:

    dataset3:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/2"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset4:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/3"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset5:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/4"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset6:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/5"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset7:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/6"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset8:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/7"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True

    dataset9:
      read_dataset:
        file_path: "data/sales_dataset/stability_index/8"
        file_type: csv
        file_configs:
          header: True
          delimiter: ","
          inferSchema: True


report_preprocessing:
  master_path: 'report_stats'
  charts_to_objects:
    list_of_cols: all
    drop_cols: Item_Identifier
    label_col: sales
    event_label: '>2k'
    bin_method: equal_frequency
    bin_size: 10
    drift_detector: True
    source_path: "NA"

report_generation:
  master_path: 'report_stats'
  id_col: 'Item_Identifier'
  label_col: 'sales'
  corr_threshold: 0.4
  iv_threshold: 0.02
  drift_threshold_model: 0.1
  dataDict_path: 'data/sales_dataset/data_dictionary.csv'
  metricDict_path: 'data/metric_dictionary.csv'
  final_report_path: 'report_stats'

write_intermediate:
  file_path: "intermediate_data"
  file_type: csv
  file_configs:
    mode: overwrite
    header: True
    delimiter: ","
    inferSchema: True

write_main:
  file_path: "output"
  file_type: parquet
  file_configs:
    mode: overwrite

write_stats:
  file_path: "stats"
  file_type: parquet
  file_configs:
    mode: overwrite
