name: Examples & Notebooks Docker Images

on:
  release:
    types: [published]
  push:
    paths:
      - 'examples/**'
    branches:
      - main


jobs:
  notebooks:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_CREDENTIALS
    strategy:
      matrix:
        include:
          - python: '3.7'
            spark: '2.4.8'
            checksum: '752C4D4D8FE1D72F5BA01F40D22DF35698585BD17ED4749F6065B0039FF40DB7FF8EA87DC0FB5B1EC03871E427A002581EC12F486392B92B88643D4243908E55'
            hadoop: '2.7'
            java: '8'
          - python: '3.9'
            spark: '3.2.0'
            checksum: 'EBE51A449EBD070BE7D3570931044070E53C23076ABAD233B3C51D45A7C99326CF55805EE0D573E6EB7D6A67CFEF1963CD77D6DC07DD2FD70FD60DA9D1F79E5E'
            hadoop: '3.2'
            java: '11'

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: anovos/anovos-notebook-${{ matrix.spark }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build image
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          SPARK_VERSION: ${{ matrix.spark }}
          SPARK_CHECKSUM: ${{ matrix.checksum }}
          HADOOP_VERSION: ${{ matrix.hadoop }}
          JDK_VERSION: ${{ matrix.java }}
        run: |
          ./examples/anovos_notebook/build_image.sh

      - name: Tag image
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo "${{ steps.meta.outputs.tags }}" | xargs -n 1 docker tag anovos-notebook-${{ matrix.spark }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        if: startsWith(github.ref, 'refs/tags')
        id: push-to-docker
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}

  examples:
    needs:
      - notebooks
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_CREDENTIALS
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        include:
          - spark: '2.4.8'
          - spark: '3.2.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: anovos/anovos-examples-${{ matrix.spark }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
            tag: ${{ github.ref }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: examples
          file: examples/Dockerfile
          build-args: |
            spark_version=${{ matrix.spark }}
            image_version=${{ steps.semver.outputs.non-prefixed }}
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
