name: Anovos Demo Docker Images

on:
  release:
    types: [published]
  push:
    paths:
      - 'demo/**'
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_CREDENTIALS

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: anovos/anovos-spark-demo
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create latest tgz
        run: |
          make clean build

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
