name: Code Quality

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '.github/workflows/lint.yml'
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Lint with flake8
        run: |
          pip install --upgrade pip
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
          src: "./src/main"
