name: Mlflow Integration

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/main/anovos/workflow.py'
      - 'config/configs_mlflow.yaml'
      - '.github/workflows/mlflow.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - python: '3.7'
            spark: '2.4.8'
            hadoop: '2.7'
            java: '8'
            experimental: false
          - python: '3.9'
            spark: '3.1.3'
            hadoop: '3.2'
            java: '11'
            experimental: false
          - python: '3.10'
            spark: '3.2.2'
            hadoop: '3.2'
            java: '11'
            experimental: false
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: ${{ matrix.spark }}
          hadoop-version: ${{ matrix.hadoop }}

      - name: Check SPARK_HOME
        run: |
          echo $SPARK_HOME
          ls $SPARK_HOME

      - name: Checkout code
        uses: actions/checkout@master

      - name: Load PIP cache
        uses: actions/cache@v3.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python}}-${{ hashFiles('./requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python}}-
            ${{ runner.os }}-pip-

      - name: Ensure clean environment
        run: |
          make clean build

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock wheel
          pip install -r requirements.txt

      - name: Set up mlflow artifact repository
        run: |
          mlflow server --backend-store-uri ./mlflow-artifacts --host 127.0.0.1 --port 8889 &

      - name: Run the demo
        run: |
          cp config/configs_mlflow.yaml dist/configs.yaml
          cd dist/
          ./spark-submit.sh

      - name: Inspect the results
        run: |
          mlflow runs list --experiment-id 1
          cd ./mlflow-artifacts
          tree
