name: Push to Branch

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/**'
      - 'requirements.txt'

jobs:
  lint:
    name: "Code Quality"
    uses: anovos/anovos/.github/workflows/lint.yml

  unit:
    name: "Unit Test"
    needs:
      - lint
    uses: anovos/anovos/.github/workflows/unit.yml

  demo:
    name: "Demo"
    needs:
      - unit
    uses: anovos/anovos/.github/workflows/demo.yml
