name: Release to PyPI
on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  build:
    name: Build the Python distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout code
        uses: actions/checkout@master

      - name: Install build tools
        run: |
          python -m pip install build --user

      - name: Build a binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .

      - name: Upload distribution
        if: startsWith(github.ref, 'refs/tags')
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: dist/
          retention-days: 7

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - build
    runs-on: ubuntu-latest
    environment: PYPI_ENV
    steps:
      - name: Download distribution
        uses: actions/download-artifact@v3
        with:
          name: distribution

      - name: Show that it's there
        run: |
          ls -lr

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: .
          verbose: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: .
          verbose: true
